/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment2;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.*;
import javafx.scene.layout.AnchorPane;
import javafx.stage.*;

import assignment2.model.*;
import java.util.HashMap;

public class App extends Application{

    private static Stage stage = null;

    @Override
    public void start(Stage stage) throws Exception {
        FXMLLoader loader = new FXMLLoader();

        // Load login page from fxml file.
        loader.setLocation(App.class.getResource("/fxml/login.fxml"));
        AnchorPane layout = (AnchorPane) loader.load();

        Scene scene = new Scene(layout);
        App.stage = stage;
        App.stage.setScene(scene);
        App.stage.setTitle("Lite Snacks");
        App.stage.show();
    }

    /**
     * Return the main stage
     */
    public static Stage getPrimaryStage() {
        return stage;
    }

    public static void main(String[] args) {
        launch(args);

    }
}
